# The deployment section should be excluded until
# it is explicitly included in module 5

# deployment:
#   dockerhub:
#     branch: master
#     commands:
#       - $DOCKER_HUB_TRIGGER

version: 2
jobs:
  build:
    docker:
      - image: centos6

test:
  override:
    - mocha 
    # test
    #  --reporter mocha-junit-reporter:
    #     environment:
    #       MOCHA_FILE: $./test-results.xml